apiVersion: apps/v1
kind: Deployment
metadata:
  name: nov23-tetris-game
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nov23-tetris-game
  template:
    metadata:
      labels:
        app: nov23-tetris-game
    spec:
      containers:
      - name: nov23-tetris-game
        image: rubinafayeen58/two-tier:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nov23-tetris-game-svc
  namespace: dev
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000 # You can choose any available port in the range 30000-32767
  selector:
    app: nov23-tetris-game
